apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: no-buildpacks-test-pipeline-5
spec:
  params:
    - name: image
      type: string
      description: image URL to push
  workspaces:
    - name: source-workspace # Directory where application source is located. (REQUIRED)
      #- name: config-workspace # Directory where configuration is located. (REQUIRED)
    - name: cache-workspace # Directory where cache is stored (OPTIONAL)
    - name: basic-auth
  tasks:
    - name: fetch-repository 
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
          subPath: app-repo
      params:
        - name: url
          #value: https://github.com/buildpacks/samples
          value: https://github.com/nikogianna/cat-app 
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
          #- name: get-sha
          #  taskRef:
          #    name: get-git-sha 
          #  runAfter: 
          #    - fetch-repository
          #  workspaces:
          #    - name: config-dir 
          #      workspace: source-workspace
          #      subPath: config-repo
          #    - name: app-dir 
          #      workspace: source-workspace
          #      subPath: app-repo
    - name: build-image
      taskRef:
        name: buildpacks
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source-workspace
          subPath: app-repo
        - name: cache
          workspace: cache-workspace
      params:
        - name: APP_IMAGE
          value: "nikogianna19/test:$(tasks.fetch-repository.results.commit)"
        - name: SOURCE_SUBPATH
          value: ""
        - name: BUILDER_IMAGE
          #value: paketobuildpacks/builder:full
          #value: paketobuildpacks/builder:full
          value: gcr.io/buildpacks/builder:v1 
    - name: fetch-config-repository # This task fetches the config repository from github
      taskRef:
        name: git-clone
      runAfter: 
        - build-image
      workspaces:
        - name: output
          workspace: source-workspace
          subPath: config-repo
      params:
        - name: url
          value: https://github.com/nikogianna/tekton-test-config
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true" 
    - name: edit-config
      runAfter: 
        - fetch-config-repository
      taskRef:
        name: hello
      workspaces:
        - name: config-dir
          workspace: source-workspace
          subPath: config-repo
        - name: app-dir
          workspace: source-workspace
          subPath: app-repo
      params:
        - name: commit-SHA-digest
          value: $(tasks.fetch-repository.results.commit)
    - name: push-to-config
      runAfter:
        - edit-config
      taskRef:
        name: git-cli
      workspaces:
        - name: source
          workspace: source-workspace
          subPath: config-repo
        - name: basic-auth
          workspace: basic-auth
      params:
        - name: GIT_USER_NAME
          value: nikogianna
        - name: GIT_USER_EMAIL
          value: nikogianna19@gmail.com
        - name: GIT_SCRIPT
          value: |
            tag=`cat $(workspaces.source.path)/shorttag.txt`
            git log --oneline
            git add .
            git commit -m "change image to $tag"
            git push origin HEAD:master
