apiVersion: v1
kind: Secret
metadata:
  name: gitsecret
type: Opaque 
stringData:
  .gitconfig: |
    [credential "https://github.com/"]
      helper = store
    [user]
      email = nikogianna19@gmail.com
      name = nikogianna
  .git-credentials: |
    https://nikogianna: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@github.com/nikogianna/tekton-test-config
