apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildpacks-test-pipeline-run-
spec:
  serviceAccountName: buildpacks-service-account # Only needed if you set up authorization
  pipelineRef:
    name: buildpacks-test-pipeline-3
  workspaces:
    - name: source-workspace
      #subPath: source
      persistentVolumeClaim:
        claimName: buildpacks-source-pvc
    - name: cache-workspace
      subPath: cache
      persistentVolumeClaim:
        claimName: buildpacks-source-pvc
  params:
    - name: image
      value: nikogianna19/test:v4 #index.docker.io/v2/nikogianna19/test #<REGISTRY/IMAGE NAME, eg gcr.io/test/image > # This defines the name of output image
